CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(225) NOT NULL UNIQUE,
    password VARCHAR(225) NOT NULL,
    fullname VARCHAR(225),
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);